apiVersion: v1
kind: ReplicationController
metadata:
   namespace: demo
   name: update-demo-rc-v1

spec:
   replicas: 2
   selector:
      demo: update
      demo_version: v1
   template:
      metadata:
         labels:
            demo: update
            demo_version: v1
      spec:
         containers:
         - name: busybox
           image: busybox
           command:
           - sh
           - -c
           - while true; do echo "$(hostname) v1" > /data/index.html; sleep 60 ; done
           volumeMounts:
           - name: content
             mountPath: /data

         - name: nginx
           image: nginx
           volumeMounts:
           - name: content
             mountPath: /usr/share/nginx/html
             readOnly: true

         volumes:
         - name: content
