apiVersion: v1
kind: ReplicationController
metadata:
   namespace: demo
   name: rc-demo-pod
   labels:
      demo: rc-pods

spec:
   replicas: 1
   selector:
      name: rc-demo
   template:
      metadata:
         labels:
            name: rc-demo
      spec:
         containers:
         - name: busybox
           image: busybox
           command:
           - sh
           - -c
           - while true; do (hostname; date) > /data/index.html; sleep 1 ; done
           volumeMounts:
           - name: content
             mountPath: /data

         - name: nginx
           image: nginx
           volumeMounts:
           - name: content
             mountPath: /usr/share/nginx/html
             readOnly: true

         volumes:
         - name: content
